### ISSUE TITLE
Could not execute GraphicsMagick/ImageMagick: gm "identify"

### ISSUE THREAD

**Issue by ankitpinl** [navjotdhanawat/dynamic-watermark#5]
Error: Could not execute GraphicsMagick/ImageMagick: gm "identify" "-ping" "-format" "%wx%h" "http://www.letuspublish.com/wp-content/uploads/2014/10/HD-Good-Morning-Wish-Pictures.jpg" this most likely means the gm/convert binaries can't be found
    at ChildProcess.<anonymous> (E:\Development\NodeJs\npm-modules\dynamic-watermark\node_modules\gm\lib\command.js:232:12)
    at emitOne (events.js:116:13)
    at ChildProcess.emit (events.js:211:7)
    at ChildProcess.cp.emit (E:\Development\NodeJs\npm-modules\dynamic-watermark\node_modules\cross-spawn\lib\enoent.js:36:37)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)

**Comment by priyankshah** [comment]
Please check already created ticket https://github.com/navjotdhanawat/dynamic-watermark/issues/1 . It may help. Generally this issue occur due to image magick not install.
